### ISSUE TITLE
Split LICENSE into CONTRIBUTING?

### ISSUE THREAD

**Issue by FeepingCreature** [etcimon/libhttp2#5]
To match https://github.com/nghttp2/nghttp2/commit/0c8ec7bfa62d0365ddb9c02b64fc157d75dcee94 upstream.

It's unclear right now whether the stuff at the bottom of LICENSE counts as license terms. nghttp2 didn't mean it like that, so they split it out into CONTRIBUTING file. Could you port that change, please? I'm looking for a http/2 client lib to use (without pulling in vibe) and having "You must provide your real name" in the *license* terms is weird.

**Comment by etcimon** [comment]
Yes, I believe those terms were mostly to encourage developers to contribute, generally I always assume that the copyrights for an MIT license are in the files themselves. I do believe github has its own system for identifying contributors so I'm not sure what to do about this myself, it looks like the AUTHORS list on nghttp/2 has nicknames too. I don't personally have a big community of contributors to this library so I'd just rely on github to list them, but I can link to the more updated list in the README.md file since I think many were responsible for the original implementation this library is based on and I'd also keep tapping into the original library when seeking optimizations in the future, even though everything works perfectly fine and fast for everything I've done with this.

**Comment by etcimon** [comment]
I don't believe Vibe has an http/2 client. I had a pull request that got buried under a lot of refactoring of the code base instead of being merged. https://github.com/vibe-d/vibe.d/pull/1160


My vibe fork has http/2 and cookies that I used regularly on very demanding workloads, built on top of the original more simple version of vibe.d but with memutils, libhttp2, libasync, openssl for tls1.3, botan, etc: https://github.com/etcimon/vibe.0

__An example http/2 request is here:__
https://github.com/etcimon/vibe.0/tree/master/examples/h2_request

Although I'm currently re-hauling it for a new project

The http/2 file (which is interconnected with fibers) is here and in client.d/server.d: https://github.com/etcimon/vibe.0/blob/master/source/vibe/http/http2.d

Also some examples of D projects that use http/2 are here: 
https://github.com/dlang/projects/issues/64

It's missing this project I think : https://github.com/adamdruppe/arsd/blob/master/http2.d
